# Generated by Django 4.2 on 2025-07-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['category', '-published_at'], name='news_news_categor_5d2cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_urgent', '-created_at'], name='news_news_is_urge_322aad_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['source', '-published_at'], name='news_news_source_3efba3_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-published_at'], name='news_news_publish_ad4867_idx'),
        ),
    ]
